export const ACTIONS = {
    SET_ORDER: 'SET_ORDER',
    SET_ORDER_BY: 'SET_ORDER_BY',
    SET_SELECTED: 'SET_SELECTED',
    SET_PAGE: 'SET_PAGE',
    SET_ROWS_PER_PAGE: 'SET_ROWS_PER_PAGE',
    SET_FILTER_BY: 'SET_FILTER_BY',
    SET_FILTER: 'SET_FILTER',
}