export const ACTIONS = {
    SET_ORDER: 'ORDER_CHANGED',
    SET_ORDER_BY: 'ORDER_BY_SELECTED',
    SET_SELECTED: 'SET_SELECTED',
    SET_PAGE: 'SET_PAGE',
    SET_ROWS_PER_PAGE: 'SET_ROWS_PER_PAGE',
    SET_FILTER_BY: 'SET_FILTER_BY',
    SET_FILTER: 'SET_FILTER',
}